#! /usr/bin/python

import sys
import subprocess

if len(sys.argv) < 2:
    print("Usage: ./runner.py <input> [--ast-on]")
    sys.exit(1)

input_data = sys.argv[1]
flags = sys.argv[2:] if len(sys.argv) > 2 else []

subprocess.run(["python3", "interp.py", input_data] + flags)