#!/usr/bin/env python3

import argparse
from src.interp import run_interpreter  

def cmd():
    argsp = argparse.ArgumentParser(
        description="FunC Interpreter",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n  refunpy contract.func -a\n  refunpy --doc"
    )

    argsp.add_argument(
        "filename",
        nargs='?',
        help="FunC source code filename (optional if --doc is used)"
    )

    argsp.add_argument(
        "-a", "--ast",
        action="store_true",
        help="enable AST output to STDOUT (requires filename)"
    )

    argsp.add_argument(
        "-e", "--env",
        action="store_true",
        help="enable ENV output to STDOUT (requires filename)"
    )

    argsp.add_argument(
        "-d", "--doc",
        action="store_true",
        help="generate documentation (can be used without filename)"
    )
        
    run_interpreter(argsp)

if __name__ == "__main__":  
    cmd()